[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.optimized"

[deploy]
startCommand = "/app/feishu_chatgpt"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = "9000"
